HumeAI/hume-react-sdk

- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/lib/client.test.ts
- packages/core/src/lib/client.ts
- packages/core/src/models/json-message.ts
- packages/core/src/models/tool-messages.ts
- packages/embed-react/package.json
- packages/embed-react/src/index.ts
- packages/embed/package.json
- packages/embed/src/index.ts
- packages/react/README.md
- packages/react/package.json
- packages/react/src/index.ts
- packages/react/src/lib/VoiceProvider.tsx
- packages/react/src/lib/useMessages.ts
- packages/react/src/lib/useVoiceClient.ts
* accept tool-related messages from the websocket
* allow users to send tool messages for function calling
> update sdk with tool message types

- examples/next-app/components/Voice.tsx
- examples/next-app/package.json
- packages/core/src/lib/client.ts
- packages/core/src/models/tool-messages.ts
- packages/react/README.md
- packages/react/src/lib/VoiceProvider.tsx
- packages/react/src/lib/useVoiceClient.ts
- pnpm-lock.yaml
* replace type coercions with zod
* misc type cleanup
> cleaning up tool types

- examples/next-app/components/Voice.tsx
- packages/core/src/lib/client.ts
- packages/core/src/models/tool-messages.ts
- packages/react/src/lib/VoiceProvider.tsx
- packages/react/src/lib/useVoiceClient.ts
- add `receivedAt` attribute to `ToolCall` message
- add `response.success` and `response.error` utilities to make sending the correct response easier
- remove async from event listener on client
> add receivedAt and response utilities for tool calling

- packages/core/package.json
- packages/embed-react/package.json
- packages/embed/package.json
- packages/react/package.json
- packages/react/src/lib/useVoiceClient.ts
> add tool call message to message history

- packages/react/src/lib/VoiceProvider.tsx
- packages/react/src/lib/useToolStatus.test.ts
- packages/react/src/lib/useToolStatus.ts
- enables components to look up the initial tool call and any resolved responses
> add tool status hook

- packages/core/package.json
- packages/core/src/lib/create-socket-config.ts
- packages/core/src/lib/create-url.test.ts
- packages/core/src/lib/create-url.ts
- packages/core/src/models/chat-metadata-message.ts
- packages/embed-react/package.json
- packages/embed/package.json
- packages/react/package.json
* enables chat metadata message
* enables query param for resuming from a previous chat group ID
> allow resuming from chat group ID

- packages/core/src/lib/create-url.test.ts
- packages/core/src/lib/create-url.ts
The flag has been removed from the backend
> remove enable_chat_metadata param

- examples/next-app/package.json
- packages/embed/package.json
- packages/react/package.json
- pnpm-lock.yaml
The new version of the Hume SDK will respect the hostname.
> (fix): bump `hume` sdk

- .github/workflows/pr-check.yml
- justfile
- packages/react/package.json
- packages/react/src/lib/VoiceProvider.test.tsx
- packages/react/src/lib/useMessages.test.ts
- packages/react/src/lib/useToolStatus.test.ts
- adds `tsc` step to `lint` to catch any typescript compiling issues with test files that may be ignored during build step
> fix tsc errors with test files

- packages/embed/src/lib/embed-messages.ts
- packages/react/src/lib/messages.ts
This PR removes directory imports that don't play nicely with ESM.
> fix: remove directory imports

- packages/embed-react/package.json
- packages/embed/package.json
- packages/react/package.json
Queue up `0.1.12-beta.4` for release
> chore: release `0.1.12-beta.4`

- examples/next-app/package.json
- packages/embed-react/package.json
- packages/embed/package.json
- packages/react/package.json
- pnpm-lock.yaml
> fix: bump hume to 0.8.8

- packages/react/src/lib/useSoundPlayer.ts
update `queueLength` whenever `clipQueue` is mutated
> fix clip queue count

- packages/react/package.json
- packages/react/src/lib/VoiceProvider.tsx
- packages/react/src/lib/connection-message.ts
- packages/react/src/lib/useMessages.test.ts
- packages/react/src/lib/useMessages.ts
- pnpm-lock.yaml
- Add `code` and `reason` to disconnect messages for increase visibility in playground
> show close event code

- examples/next-app/components/ExampleComponent.tsx
- packages/embed-react/package.json
- packages/embed/package.json
- packages/react/README.md
- packages/react/package.json
- packages/react/src/lib/VoiceProvider.tsx
Tracks whether assistant is currently paused
> track and expose isPaused property from voice provider

- examples/next-app/package.json
- examples/vite-app/package.json
- packages/embed-react/package.json
- packages/embed/package.json
- packages/react/README.md
- packages/react/package.json
- packages/react/src/lib/VoiceProvider.tsx
- packages/react/src/lib/useMessages.test.ts
- pnpm-lock.yaml
* bump hume
* enable verbose transcription (true by default)
* bump to 0.1.18-beta.1
> enable verbose transcription

- packages/react/src/lib/useSoundPlayer.ts
- packages/react/src/worklets/audio-worklet.js
Checking Garrett's worklet code into git so we have source control for it. Also moved the file to a different bucket.
> add worklet code and update path

- packages/react/src/lib/useSoundPlayer.ts
attempt to load the worklet file 10 times before considering the audio player a failure
> add worklet load retries

- examples/next-app/package.json
- examples/vite-app/package.json
- packages/embed/package.json
- packages/react/package.json
- pnpm-lock.yaml
Reverts HumeAI/empathic-voice-api-js#323
> Revert "bump hume to 0.10.4-beta.3"

- packages/react/src/lib/VoiceProvider.tsx
The websocket requires a fresh microphone stream every time it connects, because the audio headers are only present on the first chunk of a stream. However, in the case where the websocket client closes and automatically reconnects, we are currently preserving the previous microphone stream. In this PR, we update the voice provider to shut down the existing microphone and start a new stream every time a websocket connection is opened. I tested this change in all browsers and verified that the microphone works even though it's initialized inside this callback.
> create a new microphone stream for every new websocket connection

- packages/react/src/index.ts
- packages/react/src/lib/VoiceProvider.tsx
- packages/react/src/lib/useMicrophoneStream.test.ts
- packages/react/src/lib/useMicrophoneStream.ts
Now exporting useMicrophoneStream so consumers can use the hook
> export useMicrophoneStream from SDK

- examples/next-app/package.json
- examples/vite-app/package.json
- packages/embed-react/package.json
- packages/embed/package.json
- packages/react/package.json
- packages/react/src/lib/useVoiceClient.ts
- pnpm-lock.yaml
* bump hume to latest
* remove `protocol` prop (no longer needed as a public prop because hostname can include a protocol now)
> bump hume to 0.11.4

- packages/react/package.json
- packages/react/src/lib/useMicrophone.ts
- pnpm-lock.yaml
replace meyda analyzer with the same FFT analyzer we're using for output audio. meyda is outdated and emits warnings in the browser console - also adds file weight to the SDK.
> replace meyda for mic FFT

- packages/react/README.md
- Updates usage section in React package README.
- Adds link to the EVI Next.js quickstart in docs
- Updates `VoiceProvider` code snippet to no longer pass auth and config ID
- Updates `useVoice` code snippet to include access token
> updates react package readme usage section
