packages/core/package.json, packages/core/src/index.ts, packages/core/src/models/chat-metadata-message.ts, packages/core/src/models/json-message.ts, packages/embed-react/package.json, packages/embed-react/src/index.ts, packages/embed/package.json, packages/embed/src/index.ts, packages/react/package.json, packages/react/src/index.ts, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useMessages.ts, packages/react/src/lib/useVoiceClient.ts
* add support for message type `chat_metadata`
* bump version to 0.1.4 because all clients need to be updated before the corresponding backend change can be deployed
=> add support for ChatMetadataMessage

packages/react/src/lib/useSoundPlayer.ts
wraps `updateFrequencyData` logic in a try/catch which sets an empty FFT on error - handles the error thrown by browsers that don't support `getByteFrequencyData`
=> handle frequency data error

packages/core/package.json, packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/useMicrophone.ts
Turns out that setting the `enabled` property on the `MediaStreamTrack` automatically takes care of generating 0-filled frames to represent silence. We can just remove the mute check on the data handler and let it do its thing. Ref: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/enabled
=> removed muted check in mic data handler

examples/next-app/components/ExampleComponent.tsx, packages/core/src/models/chat-metadata-message.ts, packages/react/README.md, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useMessages.ts
* add request ID to ChatMetadata
* expose chat metadata message as a first-class citizen from the hook so users can reference it more easily
* fixed some hook dependency warnings
=> expose chat metadata from voice hook

examples/next-app/package.json, examples/vite-app/package.json, packages/embed/package.json, packages/react/package.json, pnpm-lock.yaml
- bumps `hume` package version from `0.8.5` to `0.8.6` to accommodate handling `assistant_end` messages in the `onMessage` handler.
=> bumps hume package version from 0.8.5 to 0.8.6

packages/react/src/lib/useVoiceClient.ts
adds check that is caught by typescript compiler to ensure all `message.type` values are handled
=> catch all message types

packages/react/src/index.ts, packages/react/src/lib/audio-message.ts, packages/react/src/lib/errors.ts, packages/react/src/lib/messages.ts
This PR reintroduces code for `parseMessageData` in the react SDK.
=> (fix): introduce errors and parse message data func

packages/react/src/lib/useMessages.ts
@zachkrall Thank you for attempting to fix this issue in your recent commits.
While the the voice client now handles `assistant_end` messages, the message store does not. This means that the `onMessage` handler passed to the `VoiceProvider` still does not support `assistant_end` messages.
I have implemented the fix here
=> fix: allow assistant end messages to be sent to parent

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useMessages.ts
set the onMessage prop as a ref so the latest callback is always called, but doesn't trigger rerenders
=> fix stale onMessage prop

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/useVoiceClient.ts
Fixes tool calling. The fern serializer was failing because it was expecting snake case, but response keys are transformed into camelcase by the fern SDK
=> remove tool response and error parser

examples/next-app/components/ExampleComponent.tsx, packages/embed-react/package.json, packages/embed/package.json, packages/react/README.md, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx
Also renames the method names because pausing the assistant now does more than just send a pause message (breaking change)
=> clear player queue when assistant is paused

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useVoiceClient.ts
This PR adds a check for readyState in each `send` method in the voice client as well as the audio capture handler. If an attempt is made after the readyState is closed, an error is thrown; this also subsequently ends up triggering disconnect cleanup tasks.
=> Add readyState check for connection closed

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx
Trying to disconnect client after it was closed was triggering a double disconnect message.
=> Only attempt to disconnect client if not closed yet

packages/react/README.md
- Updates README for `React` package (React SDK) to no longer display information in markdown tables, and instead display the information in sub headings, to make each method and prop linkable.
Link to README to see changes:
Before: https://github.com/HumeAI/empathic-voice-api-js/blob/main/packages/react/README.md 
After: https://github.com/HumeAI/empathic-voice-api-js/blob/zg/update-react-sdk-readme/packages/react/README.md
=> updates react sdk readme to no longer use markdown tables

packages/react/src/lib/useSoundPlayer.ts
Fixes issue where `isMuted` state would persist across calls
=> reset audio muted state when call ends

examples/next-app/components/Voice.tsx, packages/embed-react/package.json, packages/embed/package.json, packages/react/README.md, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useSoundPlayer.ts
These callbacks enable the client to perform some action (e.g. logging) when an audio clip starts and ends
=> add `onAudioStart`, `onAudioEnd`, and `onInterruption` callbacks 

packages/embed-react/package.json, packages/embed/package.json, packages/react/README.md, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx
One more callback to help with client-side metrics collection
=> add onAudioReceived callback to VoiceProvider

packages/react/src/lib/VoiceProvider.tsx
`sendSessionSettings` wraps `clientSessionSettings` in a try/catch - the useEffect should call `sendSessionSettings` to prevent uncaught exceptions from being thrown
=> use correct session settings method

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/useVoiceClient.ts
This ensures the handshake is complete before sending messages.
=> Wait for chat_metadata message before declaring socket open

packages/react/README.md
- Fix typo for `resumedChatGroupId` prop in React SDK package README
=> Fix typo for resumedChatGroupId prop in React SDK project README

packages/react/src/lib/useSoundPlayer.ts
Labeling the audio that comes back from EVI with `audio/mp3` is a lie. It's always WAV. We should just avoid labelling it, as putting a label on is unnecessary (the audio file has a header).
Merging it now will cause a Typescript error, need 
https://github.com/HumeAI/hume-typescript-sdk/pull/251
to be merged/released (and then will need to update this PR to reference the new version).
=> Remove mimetype

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx
Websocket connections can close both expectedly and unexpectedly; in the React SDK, there are multiple resources which are dependent on this connection state: microphone, player and the voice provider state itself. Depending on the path by which this connection is closed, either manually, server-side or erroneously, there can exist race conditions that leave some of these resources in unfitting state.
This PR implements a consolidated `handleResourceCleanup` function that orchestrates cleanup of player, microphone, and application state. Using refs to track microphone, the consolidated function can then be used in the `onClose` callback of the voice client, ensuring that all cleanup tasks properly run on different cases: manual disconnections, connection being closed server-side, or any …
=> Consolidate clean up tasks for voice audio resources

examples/next-app/components/ExampleComponent.tsx, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useSoundPlayer.test.ts, packages/react/src/lib/useSoundPlayer.ts, packages/react/src/worklets/audio-worklet.js
* bring back the `playerQueueLength` prop that was removed when the worklet was added
* with the worklet change, `isPlaying` also stopped resetting to false when the assistant stopped talking on their own. including a fix for that in this PR
https://github.com/user-attachments/assets/b1b5c59f-a997-4907-bfc3-62142715eaf2
=> bring back queue length prop and fix isPlaying state

examples/next-app/components/Voice.tsx, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useVoiceClient.test.ts, packages/react/src/lib/useVoiceClient.ts
There were a couple of areas where the SDK was making duplicate `onError` calls for the same error message - specifically, SDK was catching rejected promises by calling `onError`, while also calling `updateError`, which also calls `onError`. This PR cleans up those scenarios. 
1. Removed duplicate error that was thrown when mic permissions are denied
2. Removed duplicate error that was thrown when the websocket client error callback is called
* as part of this, we now distinguish between tool errors and client errors in the useVoiceClient hook
=> clean up some error messages

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx
When the websocket connection closes, resource cleanup happens immediately, even if there are some audio chunks still in the queue, such as a goodbye message.
This PR sets a state flag to track the player cleanup requirement, and triggers the stoppage once the queue has been fully emptied.
=> Wait for empty queue on player resource cleanup

packages/react/src/lib/VoiceProvider.tsx
The voice provider in the SDK handles resource cleanup when disconnecting or unmounting. However, in all cases the previous implementation had a delay in full cleanup because it waited for the audio queue to be empty before stopping the player. This could cause issues in scenarios where immediate cleanup is required.
- Modified handleResourceCleanup function to accept an optional forceStop parameter
- When forceStop is true, the player stops all audio immediately without waiting for the queue to empty
- Updated the disconnect function to use this immediate cleanup option
=> Make cleanup immediate on demand

examples/next-app/components/Voice.tsx, packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx
when the voice provider is unmounted, we want to stop playing all audio immediately rather than letting the queue play out
=> treat unmount as a user-initiated disconnect

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useGetMicrophoneStream.ts, packages/react/src/lib/useMicrophone.ts, packages/react/src/lib/useSoundPlayer.ts
Add reason field so it's easier for the end user to know why the error happened. Example use case: if microphone permission is denied, we would want to show a different UI state than if the mic failed to stop. User can check the `reason` field to update the UI accordingly
=> add `reason` field to `VoiceError`

examples/next-app/components/ExampleComponent.tsx, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useGetMicrophoneStream.ts
currently, the order of operations for a call is as follows:
1. we get the microphone stream so we can check for permissions
2. we connect to the websocket
3. we initialize the mic and audio player
the user can potentially disconnect the call during step 2, while the socket is connecting but the mic has not yet been initialized. if this happens, the stream never gets cleaned up. therefore, in this PR, we add a separate stopSteam function that cleans up the stream on disconnect.
=> ensure microphone stream is stopped during disconnect

examples/next-app/components/Voice.tsx, packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useSoundPlayer.test.ts, packages/react/src/lib/useSoundPlayer.ts, packages/react/src/utils/loadAudioWorklet.ts
This PR introduces the following enhancements:
- Implements a dual approach to audio processing:
- AudioWorklet Mode (default): Uses a separate thread for audio processing via AudioWorkletNode
- Regular Buffer Mode: Falls back to AudioBufferSourceNode in the main thread if worklets aren't available
- Adds a new configurable prop enableAudioWorklet to the VoiceProvider component (defaults to true)
- Restores the implementation for audio clip queuing and playback in both modes from 0.1.22
The implementation allows clients to control whether they want to use the AudioWorklet mode or the traditional buffer-based mode.
=> Enable alternative to worklet, regular buffer

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/useSoundPlayer.ts
Swaps the order of these two if statements in playNextClip. If the queue is empty, then we know we can return from the function safely and it doesn't matter if the audio context is no longer initialized. This helps address a rare race condition where the user disconnects the call immediately before an audio buffer ends.
=> move queue length check before audio context check

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useVoiceClient.ts
Two updates to prevent double connection issues:
1. prevent consumer from initializing resources again if the chat is already connected or connecting (e.g. user calls `connect` twice in a row without calling `disconnect` on the first attempt)
2. add AbortController to the websocket client so the connection attempt is canceled (e.g. the user calls `connect`, and then calls `disconnect` before the connection is established)
=> guard against double connection attempt

packages/embed-react/package.json, packages/embed/package.json, packages/react/.eslintrc.js, packages/react/package.json, packages/react/src/lib/VoiceProvider.tsx, packages/react/src/lib/useMicrophone.ts, packages/react/src/lib/useSoundPlayer.ts
PR includes a handful of changes to harden against various potential race conditions.
* Ensures each resource setup/teardown step is awaited before moving onto the next resource, instead of setting up resources in parallel. (parallelism is not possible as explained in the next bullet point)
* Updates the order in which audio player, socket, and microphone are connected and disconnected - this ensures that dependencies are always initialized first, e.g. audio player should be set up before the socket connects, socket should be connected before microphone starts sending audio. Reverse order for teardown.
* Adds guards to make sure that the audio player is connected before the socket tries to send it any audio data to the audio player.
* Adds guards to makes sure the socket is connected …
=> harden against resource setup/cleanup race conditions

examples/next-app/components/ChatConnected.tsx, packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, packages/react/src/lib/useMessages.test.ts, packages/react/src/lib/useMessages.ts
Supports adding interim user messages to the messages array so that the end user can display in-progress user message transcriptions.
1. When adding a user message to the array...
* if there is an existing interim user message, replace it with the current user message.
* otherwise, simply add the current message to the end of the array.
3. When adding any other message type...
* if there is an existing interim user message, move the existing interim message to the end of the array and insert the current message in the penultimate position.
* if there is no existing interim user message, push the current message to the end of the array
=> include interim user messages in the `messages` array

packages/embed-react/package.json, packages/embed/package.json, packages/react/package.json, pnpm-lock.yaml
Type definition updates, notably this version adds support for passing `voiceId` into `connect()` and removes support for `editable` context that doesn't work with EVI 3. (see releases https://github.com/HumeAI/hume-typescript-sdk/releases)
=> bump version of hume-typescript-sdk
